/// The levels offered by the Sudoku game, all generated by QQWing.
///
/// QQWing rates puzzles by the techniques needed to solve them; the app
/// only uses the hard end of that scale (see `src/qqwing/qqwing_ffi.cpp`):
enum SudokuDifficulty {
  /// Needs pairs, pointing pairs or box/line reductions, never a guess.
  hard('Hard'),

  /// Needs one or two guesses (trial and error).
  veryHard('Very Hard'),

  /// Needs three or more guesses.
  extreme('Extreme');

  const SudokuDifficulty(this.label);

  final String label;
}
