// Generated by package:ffigen from src/qqwing/qqwing_ffi.h. Do not edit.
// Only lib/games/sudoku/ffi/ may import this file.
// ignore_for_file: type=lint, unused_field, unused_element

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// Bindings to src/qqwing/qqwing_ffi.h (QQWing Sudoku generator).
class QqwingBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  QqwingBindings(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  QqwingBindings.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  /// Generates a puzzle with a unique solution at the requested difficulty.
  ///
  /// puzzle_out / solution_out: caller-owned buffers of QQWING_CELL_COUNT
  /// int32_t, row-major. Empty puzzle cells are 0, others 1-9.
  /// stats_out: optional (may be NULL).
  /// seed: seeds the generator, so the same seed yields the same puzzle on a
  /// given platform.
  ///
  /// Thread-safe: calls are serialised internally because QQWing draws from
  /// the process-wide rand().
  ///
  /// Returns QQWING_OK, or an error code with the buffers left untouched.
  int qqwing_generate(
    int difficulty,
    int seed,
    ffi.Pointer<ffi.Int32> puzzle_out,
    ffi.Pointer<ffi.Int32> solution_out,
    ffi.Pointer<QqwingStats> stats_out,
  ) {
    return _qqwing_generate(
      difficulty,
      seed,
      puzzle_out,
      solution_out,
      stats_out,
    );
  }

  late final _qqwing_generatePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Int32 Function(
            ffi.Int32,
            ffi.Uint32,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<ffi.Int32>,
            ffi.Pointer<QqwingStats>,
          )
        >
      >('qqwing_generate');
  late final _qqwing_generate = _qqwing_generatePtr
      .asFunction<
        int Function(
          int,
          int,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<ffi.Int32>,
          ffi.Pointer<QqwingStats>,
        )
      >();

  /// The bundled QQWing version, a static string (never free it).
  ffi.Pointer<ffi.Char> qqwing_version() {
    return _qqwing_version();
  }

  late final _qqwing_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Char> Function()>>(
        'qqwing_version',
      );
  late final _qqwing_version = _qqwing_versionPtr
      .asFunction<ffi.Pointer<ffi.Char> Function()>();
}

const int QQWING_CELL_COUNT = 81;

const int QQWING_DIFFICULTY_EXTREME = 2;

const int QQWING_DIFFICULTY_HARD = 0;

const int QQWING_DIFFICULTY_VERY_HARD = 1;

const int QQWING_ERROR_GENERATION_FAILED = 2;

const int QQWING_ERROR_INTERNAL = 3;

const int QQWING_ERROR_INVALID_ARGUMENT = 1;

const int QQWING_OK = 0;

/// How the returned puzzle rated when QQWing solved it.
final class QqwingStats extends ffi.Struct {
  @ffi.Int32()
  external int given_count;

  @ffi.Int32()
  external int single_count;

  @ffi.Int32()
  external int hidden_single_count;

  @ffi.Int32()
  external int naked_pair_count;

  @ffi.Int32()
  external int hidden_pair_count;

  @ffi.Int32()
  external int pointing_pair_triple_count;

  @ffi.Int32()
  external int box_line_reduction_count;

  @ffi.Int32()
  external int guess_count;

  @ffi.Int32()
  external int backtrack_count;

  /// Puzzles generated (and rated) before one matched the difficulty.
  @ffi.Int32()
  external int attempts;

  static ffi.Pointer<QqwingStats> $allocate(
    ffi.Allocator $allocator, {
    required int given_count,
    required int single_count,
    required int hidden_single_count,
    required int naked_pair_count,
    required int hidden_pair_count,
    required int pointing_pair_triple_count,
    required int box_line_reduction_count,
    required int guess_count,
    required int backtrack_count,
    required int attempts,
  }) => $allocator<QqwingStats>()
    ..ref.given_count = given_count
    ..ref.single_count = single_count
    ..ref.hidden_single_count = hidden_single_count
    ..ref.naked_pair_count = naked_pair_count
    ..ref.hidden_pair_count = hidden_pair_count
    ..ref.pointing_pair_triple_count = pointing_pair_triple_count
    ..ref.box_line_reduction_count = box_line_reduction_count
    ..ref.guess_count = guess_count
    ..ref.backtrack_count = backtrack_count
    ..ref.attempts = attempts;
}
