// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgsSXH98poJwNHd-k8icYdfL0sKgFCXVA',
    appId: '1:264213526650:web:f20cd8b11da713cd9da3c3',
    messagingSenderId: '264213526650',
    projectId: 'my1010-e4142',
    authDomain: 'my1010-e4142.firebaseapp.com',
    storageBucket: 'my1010-e4142.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA20n125IaF88RMRrij2EjVyG8pK4M_I2A',
    appId: '1:264213526650:android:cada09b24bd5bb399da3c3',
    messagingSenderId: '264213526650',
    projectId: 'my1010-e4142',
    storageBucket: 'my1010-e4142.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP6L4_nUPKAyxQAJ4WQjmOFWVxMMD87HM',
    appId: '1:264213526650:ios:a7b08db3ed8416569da3c3',
    messagingSenderId: '264213526650',
    projectId: 'my1010-e4142',
    storageBucket: 'my1010-e4142.firebasestorage.app',
    iosBundleId: 'com.elaybarlev.tenTenClone',
  );
}
